spring.datasource.url=jdbc: postgresql://localhost:5432/ArriendoVehículos
spring.datasource.username=postgres

# aqui ponen La contrasena que Le pusieron al postgresql
spring.datasource.password=admin
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostyreSQLDialect
spring.jpa.hibernate.ddl-auto=create
spring.jpa.open-in-view=false
#spring.jpa.hibernate.ddl-auto=create-drop