spring.datasource.url=jdbc:postgresql://localhost:5432/RentCar
spring.datasource.username=postgres

# Aqu� se establece la contrase�a que configuraste en PostgreSQL
spring.datasource.password=admin
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
#crate or update
spring.jpa.hibernate.ddl-auto = create-drop

spring.jpa.open-in-view=false
#spring.jpa.hibernate.ddl-auto=create-drop
#spring security